# Generated by Django 3.2.4 on 2022-11-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20221118_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
